version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: on-failure:5
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  db:
    driver: local
